version: "3.7"
services:
  api:
    build:
      context: /home/ubuntu/last_air_api
      dockerfile: /home/ubuntu/last_air_api/Dockerfile
    image: atla/api:1.0.0
    container_name: api
    user: "node"
    hostname: node
    ports:
      - "3000:3000"
    restart: "always"
      