version: "3.7"
services:
  api:
    build:
      context: /home/ubuntu/Huvica_Backend
      dockerfile: /home/ubuntu/Huvica_Backend/Dockerfile
    image: huvica/api:1.3.2
    container_name: api
    user: "node"
    hostname: node
    ports:
      - "3000:3000"
    restart: "always"
      